[package]
name = "bytemap-gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
noto-sans-mono-bitmap = "0.2.0"
